// Generated by CoffeeScript 1.9.3
require.config({
  baseUrl: './',
  paths: {
    jquery: 'bower_components/jquery/dist/jquery.min',
    feed: 'js/feed',
    page: 'js/page',
    lodash: 'bower_components/lodash/dist/lodash.min',
    render: 'js/render'
  }
});

require(['jquery', 'feed', 'page'], function($, feed, page) {
  var applicationStart, feeds;
  feeds = {};
  applicationStart = new Date().getTime();
  return $.get('config.json', function(config) {
    $.each(config.feeds, function(index, item) {
      feeds[item.url] = feed(item);
      return feeds[item.url].init(function() {
        return feeds[item.url].render();
      });
    });
    return page.header('#startpage-header', './templates/header.dust', config.header, function() {})();
  });
});
