// Generated by CoffeeScript 1.9.3
(function() {
  define(['jquery', 'render'], function($, render) {
    var header;
    header = function(node, template, data) {
      return render(node, template, data, function() {});
    };
    return {
      header: header
    };
  });

}).call(this);
