// Generated by CoffeeScript 1.9.3
(function() {
  define(['jquery'], function($) {
    var render;
    render = function(selector, templateFile, data, afterRender) {
      var _loadTemplate, _write;
      _loadTemplate = function(cb) {
        if (dust.cache[templateFile] !== void 0) {
          return cb();
        }
        return $.get(templateFile, function(tmpl) {
          dust.loadSource(dust.compile(tmpl, templateFile));
          return cb();
        });
      };
      _write = function(template) {
        $(selector).html(template);
        return afterRender();
      };
      return function() {
        return _loadTemplate(function() {
          return dust.render(templateFile, data, function(err, out) {
            if (!err) {
              return _write(out);
            }
          });
        });
      };
    };
    return render;
  });

}).call(this);
